// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OMG.Telemetrics.Infrastructure;

#nullable disable

namespace OMG.Telemetrics.Infrastructure.Migrations
{
    [DbContext(typeof(TelemetricsDbContext))]
    [Migration("20260302090138_RemoveHydrationRowVersion")]
    partial class RemoveHydrationRowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tele")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OMG.Telemetrics.Infrastructure.Entities.PlantHydrationStateEntity", b =>
                {
                    b.Property<Guid>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentHumidity")
                        .HasColumnType("integer");

                    b.Property<Guid>("GardenId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasIrrigationLine")
                        .HasColumnType("boolean");

                    b.Property<int>("IdealHumidityLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWatering")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastIrrigationEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastIrrigationStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlantType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PlantId");

                    b.HasIndex("GardenId");

                    b.ToTable("plant_hydration_state", "tele");
                });

            modelBuilder.Entity("OMG.Telemetrics.Infrastructure.Entities.WateringSessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GardenId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SessionId");

                    b.HasIndex("EndsAt");

                    b.HasIndex("PlantId", "Status");

                    b.ToTable("watering_sessions", "tele");
                });
#pragma warning restore 612, 618
        }
    }
}
