// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OMG.Telemetrics.Infrastructure;

#nullable disable

namespace OMG.Telemetrics.Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OMG.Telemetrics.Infrastructure.Entities.TelemetryPlantEntity", b =>
                {
                    b.Property<Guid>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentHumidityLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("GardenId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasIrrigationLine")
                        .HasColumnType("boolean");

                    b.Property<int>("IdealHumidityLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWatering")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastTelemetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeterId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PlantId");

                    b.HasIndex("GardenId");

                    b.HasIndex("MeterId");

                    b.ToTable("plants", "telemetry");
                });

            modelBuilder.Entity("OMG.Telemetrics.Infrastructure.Entities.WateringSessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId");

                    b.HasIndex("PlantId");

                    b.ToTable("watering_sessions", "telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
